import Header from './header'
import { PrismaClient } from '@prisma/client'
import { Inter } from 'next/font/google'
import './globals.css'

const prisma = new PrismaClient()
const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const categories = await prisma.category.findMany()

  return (
    <html lang="en">
      <body className={inter.className}>
        <Header
          links={
            categories.map((category) => ({ href: `/${category.slug}`, label: category.title }))
          }
        />
        <div className="w-full">
          {children}
        </div>

      </body>
    </html>
  )
}
